print(type('Hello'))
print(type(1))
print(type(1.0))
print(type(True))
print(type([1, 2, 3]))
print(type((1, 2, 3)))
print(type({1, 2, 3}))
print(type({'a': 1, 'b': 2, 'c': 3}))
print('Converted int: ',str(1))